name: baronette-data-api
services:
  baronette-data-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: baronette-data-api
    container_name: baronette-data-api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/docker/baronette/data-api/app/src
    restart: unless-stopped
    env_file:
      - .env
    networks:
     - postgres_baronette_webapp_network
     - api_webapp_network

networks:
  postgres_baronette_webapp_network:
    external: true
  api_webapp_network:
  driver: bridge